num1 = float(input('Digite um número: '))
num2 = float(input('Digite outro número: '))
nom = input('Digite seu nome: ')
print(f'Olá {nom}, tudo bem?')
print(f'A soma é: {num1 + num2}')
print(f"A subtração é: {num1 - num2}")
print(f"A multiplicação é:{num1 * num2}")
print(f"A divisão é: {num1 / num2}")